services:
  db:
    image: mysql:8.0
    container_name: toilet-mysql
    restart: always
    environment:
      MYSQL_DATABASE: toilet_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_storage:/var/lib/mysql

volumes:
  mysql_storage: