package handler

import (
	"context"
	"fmt"

	api "github.com/Neptune-Progate-Hackathon-AWS/back/internal/api"
)

// Server implements the strict server interface generated by oapi-codegen.
type Server struct{}

func NewServer() *Server {
	return &Server{}
}

// Ensure Server implements the interface at compile time.
var _ api.StrictServerInterface = (*Server)(nil)

var errNotImplemented = fmt.Errorf("not implemented")

func (s *Server) ConfirmSignUp(ctx context.Context, request api.ConfirmSignUpRequestObject) (api.ConfirmSignUpResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) Login(ctx context.Context, request api.LoginRequestObject) (api.LoginResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) Logout(ctx context.Context, request api.LogoutRequestObject) (api.LogoutResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) RefreshToken(ctx context.Context, request api.RefreshTokenRequestObject) (api.RefreshTokenResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) SignUp(ctx context.Context, request api.SignUpRequestObject) (api.SignUpResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) CreatePresignedUrl(ctx context.Context, request api.CreatePresignedUrlRequestObject) (api.CreatePresignedUrlResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) GetRoute(ctx context.Context, request api.GetRouteRequestObject) (api.GetRouteResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) UnregisterDevice(ctx context.Context, request api.UnregisterDeviceRequestObject) (api.UnregisterDeviceResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) RegisterDevice(ctx context.Context, request api.RegisterDeviceRequestObject) (api.RegisterDeviceResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) CheckLocationAlert(ctx context.Context, request api.CheckLocationAlertRequestObject) (api.CheckLocationAlertResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) ListStores(ctx context.Context, request api.ListStoresRequestObject) (api.ListStoresResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) ListToilets(ctx context.Context, request api.ListToiletsRequestObject) (api.ListToiletsResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) CreateToilet(ctx context.Context, request api.CreateToiletRequestObject) (api.CreateToiletResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) GetToilet(ctx context.Context, request api.GetToiletRequestObject) (api.GetToiletResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) ListReports(ctx context.Context, request api.ListReportsRequestObject) (api.ListReportsResponseObject, error) {
	return nil, errNotImplemented
}

func (s *Server) CreateReport(ctx context.Context, request api.CreateReportRequestObject) (api.CreateReportResponseObject, error) {
	return nil, errNotImplemented
}
