package handler

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/google/uuid"

	api "github.com/Neptune-Progate-Hackathon-AWS/back/internal/api"
)

// Server implements the strict server interface generated by oapi-codegen.
type Server struct{
    dynamoClient *dynamodb.Client // AWSと通信するためのクライアントを追加
}

func NewServer(client *dynamodb.Client) *Server {
    return &Server{
        dynamoClient: client,
    }
}

// Ensure Server implements the interface at compile time.
var _ api.StrictServerInterface = (*Server)(nil)

var errNotImplemented = fmt.Errorf("not implemented")

// =========================================================================
// ここから下が、最新の設計図（openapi.yml）に合わせたAPIの受付窓口です
// 4つの役割（関数）だけになりました！
// =========================================================================

// 1. 【画像アップロード】S3に画像を保存するための専用URLを発行する関数
// POST /images/presigned-url
func (s *Server) CreatePresignedUrl(ctx context.Context, request api.CreatePresignedUrlRequestObject) (api.CreatePresignedUrlResponseObject, error) {
	return nil, errNotImplemented // まだ作っていないので「未実装」エラーを返す
}

// 2. 【トイレ登録】トイレの情報を新しく登録する関数
// POST /toilets
func (s *Server) CreateToilet(ctx context.Context, request api.CreateToiletRequestObject) (api.CreateToiletResponseObject, error) {
    // 1. 保存するデータの「塊」を作る
    // 設計図(request.Body)のデータを、DB保存用の形式に整理します
    item := map[string]interface{}{
        "toiletId":           uuid.New().String(), // ここで本物のランダムなIDを生成！
        "name":               request.Body.Name,
        "brand":              string(request.Body.Brand),
        "lat":                request.Body.Lat,
        "lng":                request.Body.Lng,
        "imageKey":           request.Body.ImageKey,
        "maleCount":          request.Body.MaleCount,
        "femaleCount":        request.Body.FemaleCount,
        "multipurposeCount":  request.Body.MultipurposeCount,
        "requiresPermission": request.Body.RequiresPermission,
        "createdAt":          time.Now().Format(time.RFC3339),
    }

    // 2. GoのデータをDynamoDBが理解できる形式に変換（Marshal）
    av, err := attributevalue.MarshalMap(item)
    if err != nil {
        return nil, fmt.Errorf("failed to marshal item: %w", err)
    }

    // 3. DynamoDBに「これ保存して！」とお願いする（PutItem）
    _, err = s.dynamoClient.PutItem(ctx, &dynamodb.PutItemInput{
        TableName: aws.String("ToiletsTable"), // 保存先のテーブル名
        Item:      av,
    })
    if err != nil {
        return nil, fmt.Errorf("failed to put item to DynamoDB: %w", err)
    }

    // 4. 成功レスポンスを返す
    return api.CreateToilet201JSONResponse{
        // ... (以下、先ほどと同じレスポンス処理)
    }, nil
}

// 3. 【トイレ検索】指定した範囲内にあるトイレの一覧をまとめて取得する関数（マップ表示用）
// GET /toilets
func (s *Server) ListToilets(ctx context.Context, request api.ListToiletsRequestObject) (api.ListToiletsResponseObject, error) {
	return nil, errNotImplemented // まだ作っていないので「未実装」エラーを返す
}

// 4. 【トイレ詳細取得】特定のトイレIDを指定して、そのトイレの詳しい情報を取得する関数
// GET /toilets/{toiletId}
func (s *Server) GetToilet(ctx context.Context, request api.GetToiletRequestObject) (api.GetToiletResponseObject, error) {
	return nil, errNotImplemented // まだ作っていないので「未実装」エラーを返す
}