// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CognitoAuthScopes = "cognitoAuth.Scopes"
)

// Defines values for CreateToiletRequestBrand.
const (
	CreateToiletRequestBrandDailyYamazaki CreateToiletRequestBrand = "daily_yamazaki"
	CreateToiletRequestBrandFamilyMart    CreateToiletRequestBrand = "family_mart"
	CreateToiletRequestBrandLawson        CreateToiletRequestBrand = "lawson"
	CreateToiletRequestBrandMiniStop      CreateToiletRequestBrand = "mini_stop"
	CreateToiletRequestBrandOther         CreateToiletRequestBrand = "other"
	CreateToiletRequestBrandSevenEleven   CreateToiletRequestBrand = "seven_eleven"
)

// Valid indicates whether the value is a known member of the CreateToiletRequestBrand enum.
func (e CreateToiletRequestBrand) Valid() bool {
	switch e {
	case CreateToiletRequestBrandDailyYamazaki:
		return true
	case CreateToiletRequestBrandFamilyMart:
		return true
	case CreateToiletRequestBrandLawson:
		return true
	case CreateToiletRequestBrandMiniStop:
		return true
	case CreateToiletRequestBrandOther:
		return true
	case CreateToiletRequestBrandSevenEleven:
		return true
	default:
		return false
	}
}

// Defines values for CreateToiletRequestToiletType.
const (
	CreateToiletRequestToiletTypeSeparated CreateToiletRequestToiletType = "separated"
	CreateToiletRequestToiletTypeShared    CreateToiletRequestToiletType = "shared"
)

// Valid indicates whether the value is a known member of the CreateToiletRequestToiletType enum.
func (e CreateToiletRequestToiletType) Valid() bool {
	switch e {
	case CreateToiletRequestToiletTypeSeparated:
		return true
	case CreateToiletRequestToiletTypeShared:
		return true
	default:
		return false
	}
}

// Defines values for PresignedUrlRequestContentType.
const (
	Imagejpeg PresignedUrlRequestContentType = "image/jpeg"
	Imagepng  PresignedUrlRequestContentType = "image/png"
	Imagewebp PresignedUrlRequestContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the PresignedUrlRequestContentType enum.
func (e PresignedUrlRequestContentType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for ToiletBrand.
const (
	ToiletBrandDailyYamazaki ToiletBrand = "daily_yamazaki"
	ToiletBrandFamilyMart    ToiletBrand = "family_mart"
	ToiletBrandLawson        ToiletBrand = "lawson"
	ToiletBrandMiniStop      ToiletBrand = "mini_stop"
	ToiletBrandOther         ToiletBrand = "other"
	ToiletBrandSevenEleven   ToiletBrand = "seven_eleven"
)

// Valid indicates whether the value is a known member of the ToiletBrand enum.
func (e ToiletBrand) Valid() bool {
	switch e {
	case ToiletBrandDailyYamazaki:
		return true
	case ToiletBrandFamilyMart:
		return true
	case ToiletBrandLawson:
		return true
	case ToiletBrandMiniStop:
		return true
	case ToiletBrandOther:
		return true
	case ToiletBrandSevenEleven:
		return true
	default:
		return false
	}
}

// Defines values for ToiletToiletType.
const (
	ToiletToiletTypeSeparated ToiletToiletType = "separated"
	ToiletToiletTypeShared    ToiletToiletType = "shared"
)

// Valid indicates whether the value is a known member of the ToiletToiletType enum.
func (e ToiletToiletType) Valid() bool {
	switch e {
	case ToiletToiletTypeSeparated:
		return true
	case ToiletToiletTypeShared:
		return true
	default:
		return false
	}
}

// CreateToiletRequest defines model for CreateToiletRequest.
type CreateToiletRequest struct {
	// Address 住所
	Address *string `json:"address,omitempty"`

	// Brand コンビニブランド
	Brand CreateToiletRequestBrand `json:"brand"`

	// ImageKey S3にアップロード済みの画像キー
	ImageKey *string `json:"imageKey,omitempty"`

	// Lat 緯度
	Lat float64 `json:"lat"`

	// Lng 経度
	Lng float64 `json:"lng"`

	// Name コンビニ店舗名
	Name string `json:"name"`

	// Note その他自由記入欄
	Note *string `json:"note,omitempty"`

	// RequiresPermission 店員への使用許可が必要か
	RequiresPermission bool `json:"requiresPermission"`

	// ToiletType shared: 男女共用, separated: 男女別
	ToiletType CreateToiletRequestToiletType `json:"toiletType"`
}

// CreateToiletRequestBrand コンビニブランド
type CreateToiletRequestBrand string

// CreateToiletRequestToiletType shared: 男女共用, separated: 男女別
type CreateToiletRequestToiletType string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PresignedUrlRequest defines model for PresignedUrlRequest.
type PresignedUrlRequest struct {
	// ContentType アップロードする画像のMIMEタイプ
	ContentType PresignedUrlRequestContentType `json:"contentType"`
}

// PresignedUrlRequestContentType アップロードする画像のMIMEタイプ
type PresignedUrlRequestContentType string

// PresignedUrlResponse defines model for PresignedUrlResponse.
type PresignedUrlResponse struct {
	// ExpiresIn URL有効期限（秒）
	ExpiresIn int `json:"expiresIn"`

	// ImageKey S3オブジェクトキー（投稿時に指定）
	ImageKey string `json:"imageKey"`

	// UploadUrl S3 presigned PUT URL
	UploadUrl string `json:"uploadUrl"`
}

// Toilet defines model for Toilet.
type Toilet struct {
	Address   *string     `json:"address,omitempty"`
	Brand     ToiletBrand `json:"brand"`
	CreatedAt time.Time   `json:"createdAt"`

	// CreatedBy 投稿者ユーザーID
	CreatedBy *string `json:"createdBy,omitempty"`

	// ImageUrl トイレ画像URL
	ImageUrl string  `json:"imageUrl"`
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`

	// Name コンビニ店舗名
	Name               string             `json:"name"`
	Note               *string            `json:"note,omitempty"`
	RequiresPermission bool               `json:"requiresPermission"`
	ToiletId           openapi_types.UUID `json:"toiletId"`

	// ToiletType shared: 男女共用, separated: 男女別
	ToiletType ToiletToiletType `json:"toiletType"`
	UpdatedAt  *time.Time       `json:"updatedAt,omitempty"`
}

// ToiletBrand defines model for Toilet.Brand.
type ToiletBrand string

// ToiletToiletType shared: 男女共用, separated: 男女別
type ToiletToiletType string

// ToiletId defines model for toiletId.
type ToiletId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListToiletsParams defines parameters for ListToilets.
type ListToiletsParams struct {
	// Lat 中心緯度
	Lat float64 `form:"lat" json:"lat"`

	// Lng 中心経度
	Lng float64 `form:"lng" json:"lng"`

	// Radius 検索半径（メートル）
	Radius *int `form:"radius,omitempty" json:"radius,omitempty"`
}

// CreatePresignedUrlJSONRequestBody defines body for CreatePresignedUrl for application/json ContentType.
type CreatePresignedUrlJSONRequestBody = PresignedUrlRequest

// CreateToiletJSONRequestBody defines body for CreateToilet for application/json ContentType.
type CreateToiletJSONRequestBody = CreateToiletRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(w http.ResponseWriter, r *http.Request)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams)
	// トイレ情報を投稿
	// (POST /toilets)
	CreateToilet(w http.ResponseWriter, r *http.Request)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// S3 presigned URL を発行
// (POST /images/presigned-url)
func (_ Unimplemented) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 指定範囲内のトイレ一覧を取得（マップ表示用）
// (GET /toilets)
func (_ Unimplemented) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ情報を投稿
// (POST /toilets)
func (_ Unimplemented) CreateToilet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ詳細を取得
// (GET /toilets/{toiletId})
func (_ Unimplemented) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreatePresignedUrl operation middleware
func (siw *ServerInterfaceWrapper) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePresignedUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListToilets operation middleware
func (siw *ServerInterfaceWrapper) ListToilets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToiletsParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := r.URL.Query().Get("lat"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		return
	}

	// ------------- Required query parameter "lng" -------------

	if paramValue := r.URL.Query().Get("lng"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListToilets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToilet operation middleware
func (siw *ServerInterfaceWrapper) CreateToilet(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToilet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToilet operation middleware
func (siw *ServerInterfaceWrapper) GetToilet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToilet(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/images/presigned-url", wrapper.CreatePresignedUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets", wrapper.ListToilets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/toilets", wrapper.CreateToilet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets/{toiletId}", wrapper.GetToilet)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type CreatePresignedUrlRequestObject struct {
	Body *CreatePresignedUrlJSONRequestBody
}

type CreatePresignedUrlResponseObject interface {
	VisitCreatePresignedUrlResponse(w http.ResponseWriter) error
}

type CreatePresignedUrl200JSONResponse PresignedUrlResponse

func (response CreatePresignedUrl200JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrl401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePresignedUrl401JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListToiletsRequestObject struct {
	Params ListToiletsParams
}

type ListToiletsResponseObject interface {
	VisitListToiletsResponse(w http.ResponseWriter) error
}

type ListToilets200JSONResponse struct {
	Toilets []Toilet `json:"toilets"`
}

func (response ListToilets200JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListToilets401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListToilets401JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateToiletRequestObject struct {
	Body *CreateToiletJSONRequestBody
}

type CreateToiletResponseObject interface {
	VisitCreateToiletResponse(w http.ResponseWriter) error
}

type CreateToilet201JSONResponse Toilet

func (response CreateToilet201JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateToilet400JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateToilet401JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetToiletRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
}

type GetToiletResponseObject interface {
	VisitGetToiletResponse(w http.ResponseWriter) error
}

type GetToilet200JSONResponse Toilet

func (response GetToilet200JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetToilet401JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet404JSONResponse struct{ NotFoundJSONResponse }

func (response GetToilet404JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(ctx context.Context, request CreatePresignedUrlRequestObject) (CreatePresignedUrlResponseObject, error)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(ctx context.Context, request ListToiletsRequestObject) (ListToiletsResponseObject, error)
	// トイレ情報を投稿
	// (POST /toilets)
	CreateToilet(ctx context.Context, request CreateToiletRequestObject) (CreateToiletResponseObject, error)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(ctx context.Context, request GetToiletRequestObject) (GetToiletResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreatePresignedUrl operation middleware
func (sh *strictHandler) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	var request CreatePresignedUrlRequestObject

	var body CreatePresignedUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresignedUrl(ctx, request.(CreatePresignedUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresignedUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePresignedUrlResponseObject); ok {
		if err := validResponse.VisitCreatePresignedUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListToilets operation middleware
func (sh *strictHandler) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	var request ListToiletsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListToilets(ctx, request.(ListToiletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListToilets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListToiletsResponseObject); ok {
		if err := validResponse.VisitListToiletsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToilet operation middleware
func (sh *strictHandler) CreateToilet(w http.ResponseWriter, r *http.Request) {
	var request CreateToiletRequestObject

	var body CreateToiletJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToilet(ctx, request.(CreateToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateToiletResponseObject); ok {
		if err := validResponse.VisitCreateToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetToilet operation middleware
func (sh *strictHandler) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request GetToiletRequestObject

	request.ToiletId = toiletId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetToilet(ctx, request.(GetToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToiletResponseObject); ok {
		if err := validResponse.VisitGetToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZbVMbxx3/KjfbvminFyRK8kbvcOxkSEjCYKhfUMaz6BZxju7Be3u2ZUYz3J1phIHa",
	"4xCrNLSuUwwyjkUIbk14MB9mOZ38yl+hs7un00k6Ieo4tK+4Pd3+H/b/8Pv9l1mQNTTT0JFOLJCZBSbE",
	"UEMEYb4ihppHZEhhzwqyslg1iWroIAOoV6LuOvW+H7oIZKCyVyYkM0AGOtQQyDS3ygCj67aKkQIyBNtI",
	"BlZ2BmmQyZw2sAYJyADbVtmXpGCyvRbBqp4DxWKRbbZMQ7cQt+cCVEbRdRtZhK2yhk6Qzh+haebVLGTG",
	"pa5ZzMLZmJpfYzQNMuBXqaavKfGrlbqEsYGFqnYPt6i7Td0KdX+iXulkb7n2/J+gKIPPDfKRYevKOZlw",
	"RL1DZoKzVN9YpM46dRapu0CdLercYeaM69AmMwZWb6NzMKm+tVyvHLJT8Z5S7xCwL8JNTOaHGEGCxnjs",
	"Y5EysWEiTFQRRagoGFlWZ1KdHN2rLcx15oEMpjDUk7LQ3aXeLvW+pt4i9R5ym3aptwBkgHRbA5kJYKEb",
	"SL+K8uwPkME01NR84aoGMQEyyMOb7FhkoKm6etUihglkoED2RQFq8Db8UgUyMMgMwmAywSxVgzn0KSp0",
	"WnZ5gDrPqPsd9Tzqlan3nEXRW6jtlahzTJ1qsHLge/eoy94nOZyHpFNo8HLb399gXjTqRjHsqTxqCtBt",
	"bQphLkDPJQj419KZBYg6Pu3E/f1yvVT27y+z474FNTOP+BcHPBS774kGIRZSbW+x/sPL15vz/sKyv19O",
	"8lk3SJJG52/UqZ4cPKx/tRWs7NQrf/Hnn9S+v8OiBm8NIz1HZkDmg3Q6QWLYeawRhDXVslRRAq3y/f2y",
	"//Vj6uwxLUfHwUqlXtnx721TZ8k/nq9vONRZbFo7ZRh5BHUmXHS4Mf6+Xag1AzFSMlKw8tJ/suvP7wQr",
	"FVmyEGuvJPZD6Uk8VfkmIIPou4SkK8b76YSIUqM+RNqI2LfYl3gSTdnG1DWUJcwnUfcdFZs1FO5kM8p/",
	"GBweujg4NvTF51cvjY5+MZoUTw1ZFsy1bWxrq9RZEp2VOpvUWQW9/OWWNEUn+TCCkaXmdKSM43zXHhR2",
	"yeToddYtdVapuxgWrVP9bOizS9Q95glejkWQ94PUNROx8xcLU28+30RTZu+Qxk3r7Z9Ax04H0S2TxXso",
	"IePHR4drawv+3Z9qa49er95/c1gKNh+8OVyIl/FArJ5UnaCcaAqnNjx3i9W6u0fdTRZixhDY8b05LNXu",
	"fhNUjmurLnWe1Za+8qt/Feo6UsY28wZkjiUpkMyG59LI+Jg0Pjoc72Q2VntmT1N8zBU5dlZJ5y3Q7FQY",
	"645X5wJDWY66yiBp4VQKJOg9omoIdN9yISGSIlj1uXnqbXDu8W/qHXKal4x/idGK+KGombPEKgK9s6Pb",
	"/zWMnRGNugGLYN09GPL/CoVYpSr/Xc61lWJsPjgFw6IE6w1n8TLoLGNGU1HWxiopXGZ0tYECOV0lxqDN",
	"KMQsmEIQI/xRw5lProyBdv47qMHbhi59KDZK1FkKVvfrj5cEQEhDF6Ux40ukSylpMJtFliWWICTJPNBc",
	"SfN8ZggxBdNW9WmjB8d1qlFhnRwtB0fVmjfv/2OHug/8+Z3a2gL1Dmrra8GL74Q9V9AUx7IyR90dXs0v",
	"qbfJBDrVwZEhOuf+UQ85vbNNvW844u1yYGZjRuTo5YufStR9EHz7ovbnJ37pabBS4Xupd59BpUB0zr2p",
	"sy0NjgxJH0OCbsKCRJ1qJGWwMalgiTqb0idXxpjQ2voa08/EsWNRSViAcW5falTh3wUyMxVABjcQFnUE",
	"+vvSfWmWmIaJdGiqIAMG+tJ9A0DmgykPd4qnk5WKcOQ9W/Qu0xAcgbV3Pi6x4guHmTjchpmHLHLBUArv",
	"bNpKYizF1oJhk3P7NPz7dPoXMiEkFQnzXxOCx0eHJZH7tdJ9/+4jdvbvp/u7KYosT7UMrPHCBJmJtpKc",
	"mCxOysCyNQ3iQjsHYAawlOQ2sMSBOSsiYRaYZKJTomvw48qhhBgPqxYZC7+RW24/Jjqm073n/rEXzWD8",
	"zuO6jXCheekhWtcZ7ju64VVR7qK1MbglauWt8p1qFU3EX77rv7rz5rBEvcecB5eo90wwtyQ7MFRU2wJx",
	"1QqahnaegEx/mhFKDd5SNQYzH4ilqotlfxLbZKH/WfneStdimaASpFm9KiKkfcXIMIgxLHTBMSsJchLu",
	"cxq9e2+uvrF5HhUj2Hawfcf/9kf/T/MtAMKNYNBx76H/qszDHHbX+uNKsL4frFRCmh5WVuRrUY5a5qlg",
	"JahViFFOJVIdoRZ1XrH3rkOdDcE7BXBxMGiMW9sn+4v+wjJ1nkmXByQ2qSfMZ2U65whH2LPzSGrwe44w",
	"/BRiooGc2OvDmP8yXT7pbuxMXb7/nZnQyOnO1AwntFgnT/fOy9h17Dmkcmf2CKMTEzTW+1OzDa5Z7AoD",
	"HyMSxb4NBJL8aX6Sinjsz25Xbxe46FTqT3eDFz+8ZSDYpvd7b4quvt8ycsLGqOUkR46LxjeSQXgEG4qd",
	"ZQvpN3GW+TtpGGpTCvwtkAEndZxXW5lUCppqXzjW9WUNLXWjn4cqVNx1bm00rWqwevB66UfqHUQ2t/yH",
	"wwKd6Nm43G3vUs29IUcpThb/EwAA//9V44t+gRkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
