// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CognitoAuthScopes = "cognitoAuth.Scopes"
)

// Defines values for DeviceRegistrationRequestPlatform.
const (
	Android DeviceRegistrationRequestPlatform = "android"
	Ios     DeviceRegistrationRequestPlatform = "ios"
	Web     DeviceRegistrationRequestPlatform = "web"
)

// Valid indicates whether the value is a known member of the DeviceRegistrationRequestPlatform enum.
func (e DeviceRegistrationRequestPlatform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for PresignedUrlRequestContentType.
const (
	Imagejpeg PresignedUrlRequestContentType = "image/jpeg"
	Imagepng  PresignedUrlRequestContentType = "image/png"
	Imagewebp PresignedUrlRequestContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the PresignedUrlRequestContentType enum.
func (e PresignedUrlRequestContentType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for PresignedUrlRequestPurpose.
const (
	ToiletRegistration PresignedUrlRequestPurpose = "toilet_registration"
	ToiletReport       PresignedUrlRequestPurpose = "toilet_report"
)

// Valid indicates whether the value is a known member of the PresignedUrlRequestPurpose enum.
func (e PresignedUrlRequestPurpose) Valid() bool {
	switch e {
	case ToiletRegistration:
		return true
	case ToiletReport:
		return true
	default:
		return false
	}
}

// Defines values for ReportStatus.
const (
	Accepted ReportStatus = "accepted"
	Rejected ReportStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ReportStatus enum.
func (e ReportStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for StoreBrand.
const (
	DailyYamazaki StoreBrand = "daily_yamazaki"
	FamilyMart    StoreBrand = "family_mart"
	Lawson        StoreBrand = "lawson"
	MiniStop      StoreBrand = "mini_stop"
	Other         StoreBrand = "other"
	SevenEleven   StoreBrand = "seven_eleven"
)

// Valid indicates whether the value is a known member of the StoreBrand enum.
func (e StoreBrand) Valid() bool {
	switch e {
	case DailyYamazaki:
		return true
	case FamilyMart:
		return true
	case Lawson:
		return true
	case MiniStop:
		return true
	case Other:
		return true
	case SevenEleven:
		return true
	default:
		return false
	}
}

// Defines values for ToiletStatus.
const (
	Active  ToiletStatus = "active"
	Removed ToiletStatus = "removed"
)

// Valid indicates whether the value is a known member of the ToiletStatus enum.
func (e ToiletStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Removed:
		return true
	default:
		return false
	}
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn アクセストークン有効期限（秒）
	ExpiresIn    int    `json:"expiresIn"`
	IdToken      string `json:"idToken"`
	RefreshToken string `json:"refreshToken"`
}

// ConfirmSignUpRequest defines model for ConfirmSignUpRequest.
type ConfirmSignUpRequest struct {
	ConfirmationCode string              `json:"confirmationCode"`
	Email            openapi_types.Email `json:"email"`
}

// CreateReportRequest defines model for CreateReportRequest.
type CreateReportRequest struct {
	// ImageKey 「トイレなし」証拠画像のS3キー
	ImageKey string `json:"imageKey"`

	// Reason 報告理由
	Reason string `json:"reason"`
}

// CreateToiletRequest defines model for CreateToiletRequest.
type CreateToiletRequest struct {
	// FemaleCount 女性用トイレ個数
	FemaleCount int `json:"femaleCount"`

	// ImageKey S3にアップロード済みの画像キー
	ImageKey string `json:"imageKey"`

	// MaleCount 男性用トイレ個数
	MaleCount int `json:"maleCount"`

	// MultipurposeCount 多目的トイレ個数
	MultipurposeCount int `json:"multipurposeCount"`

	// Note その他自由記入欄
	Note *string `json:"note,omitempty"`

	// RequiresPermission 店員への使用許可が必要か
	RequiresPermission bool `json:"requiresPermission"`

	// StoreId コンビニ店舗ID
	StoreId openapi_types.UUID `json:"storeId"`
}

// DeviceRegistrationRequest defines model for DeviceRegistrationRequest.
type DeviceRegistrationRequest struct {
	// DeviceToken FCM / APNs デバイストークン
	DeviceToken string                            `json:"deviceToken"`
	Platform    DeviceRegistrationRequestPlatform `json:"platform"`
}

// DeviceRegistrationRequestPlatform defines model for DeviceRegistrationRequest.Platform.
type DeviceRegistrationRequestPlatform string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LocationCheckRequest defines model for LocationCheckRequest.
type LocationCheckRequest struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// LocationCheckResponse defines model for LocationCheckResponse.
type LocationCheckResponse struct {
	// HasNearbyToilet 1km以内にトイレがあるか
	HasNearbyToilet bool `json:"hasNearbyToilet"`

	// NearestToilet 最寄りのトイレ（なければnull）
	NearestToilet *Toilet `json:"nearestToilet"`

	// NotificationSent トイレ不在通知を送信したか
	NotificationSent *bool `json:"notificationSent,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PresignedUrlRequest defines model for PresignedUrlRequest.
type PresignedUrlRequest struct {
	// ContentType アップロードする画像のMIMEタイプ
	ContentType PresignedUrlRequestContentType `json:"contentType"`

	// Purpose 画像の用途
	Purpose PresignedUrlRequestPurpose `json:"purpose"`
}

// PresignedUrlRequestContentType アップロードする画像のMIMEタイプ
type PresignedUrlRequestContentType string

// PresignedUrlRequestPurpose 画像の用途
type PresignedUrlRequestPurpose string

// PresignedUrlResponse defines model for PresignedUrlResponse.
type PresignedUrlResponse struct {
	// ExpiresIn URL有効期限（秒）
	ExpiresIn int `json:"expiresIn"`

	// ImageKey S3オブジェクトキー（投稿時に指定）
	ImageKey string `json:"imageKey"`

	// UploadUrl S3 presigned PUT URL
	UploadUrl string `json:"uploadUrl"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Report defines model for Report.
type Report struct {
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy *string            `json:"createdBy,omitempty"`
	ImageUrl  string             `json:"imageUrl"`
	Reason    string             `json:"reason"`
	ReportId  openapi_types.UUID `json:"reportId"`

	// Status accepted=Rekognition審査通過, rejected=不通過
	Status   ReportStatus       `json:"status"`
	ToiletId openapi_types.UUID `json:"toiletId"`
}

// ReportStatus accepted=Rekognition審査通過, rejected=不通過
type ReportStatus string

// RouteDetail defines model for RouteDetail.
type RouteDetail struct {
	// DistanceMeters 距離（メートル）
	DistanceMeters float64 `json:"distanceMeters"`

	// DurationSeconds 所要時間（秒）
	DurationSeconds int `json:"durationSeconds"`

	// Polyline エンコード済みポリライン（地図描画用）
	Polyline string `json:"polyline"`
	Toilet   Toilet `json:"toilet"`
}

// RouteRequest defines model for RouteRequest.
type RouteRequest struct {
	// Lat 現在位置の緯度
	Lat float64 `json:"lat"`

	// Lng 現在位置の経度
	Lng float64 `json:"lng"`

	// MaxResults 提案するトイレの最大数
	MaxResults *int `json:"maxResults,omitempty"`
}

// RouteResponse defines model for RouteResponse.
type RouteResponse struct {
	Routes []RouteDetail `json:"routes"`

	// Suggestion Bedrock が生成した提案文
	Suggestion string `json:"suggestion"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	Nickname string              `json:"nickname"`
	Password string              `json:"password"`
}

// Store defines model for Store.
type Store struct {
	Address *string    `json:"address,omitempty"`
	Brand   StoreBrand `json:"brand"`

	// HasToilet トイレ情報が登録済みかどうか
	HasToilet *bool              `json:"hasToilet,omitempty"`
	Lat       float64            `json:"lat"`
	Lng       float64            `json:"lng"`
	Name      string             `json:"name"`
	StoreId   openapi_types.UUID `json:"storeId"`
}

// StoreBrand defines model for Store.Brand.
type StoreBrand string

// Toilet defines model for Toilet.
type Toilet struct {
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy 投稿者ユーザーID
	CreatedBy   *string `json:"createdBy,omitempty"`
	FemaleCount int     `json:"femaleCount"`

	// ImageUrl トイレ画像URL
	ImageUrl          string  `json:"imageUrl"`
	MaleCount         int     `json:"maleCount"`
	MultipurposeCount int     `json:"multipurposeCount"`
	Note              *string `json:"note,omitempty"`

	// ReportCount 虚偽報告の件数
	ReportCount        int  `json:"reportCount"`
	RequiresPermission bool `json:"requiresPermission"`

	// Status active=マップ表示中, removed=虚偽報告により削除
	Status    ToiletStatus       `json:"status"`
	StoreId   openapi_types.UUID `json:"storeId"`
	ToiletId  openapi_types.UUID `json:"toiletId"`
	UpdatedAt *time.Time         `json:"updatedAt,omitempty"`
}

// ToiletStatus active=マップ表示中, removed=虚偽報告により削除
type ToiletStatus string

// ToiletId defines model for toiletId.
type ToiletId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListStoresParams defines parameters for ListStores.
type ListStoresParams struct {
	// Lat 中心緯度
	Lat float64 `form:"lat" json:"lat"`

	// Lng 中心経度
	Lng float64 `form:"lng" json:"lng"`

	// Radius 検索半径（メートル）
	Radius *int `form:"radius,omitempty" json:"radius,omitempty"`
}

// ListToiletsParams defines parameters for ListToilets.
type ListToiletsParams struct {
	Lat    float64 `form:"lat" json:"lat"`
	Lng    float64 `form:"lng" json:"lng"`
	Radius *int    `form:"radius,omitempty" json:"radius,omitempty"`
}

// ConfirmSignUpJSONRequestBody defines body for ConfirmSignUp for application/json ContentType.
type ConfirmSignUpJSONRequestBody = ConfirmSignUpRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// CreatePresignedUrlJSONRequestBody defines body for CreatePresignedUrl for application/json ContentType.
type CreatePresignedUrlJSONRequestBody = PresignedUrlRequest

// GetRouteJSONRequestBody defines body for GetRoute for application/json ContentType.
type GetRouteJSONRequestBody = RouteRequest

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistrationRequest

// CheckLocationAlertJSONRequestBody defines body for CheckLocationAlert for application/json ContentType.
type CheckLocationAlertJSONRequestBody = LocationCheckRequest

// CreateToiletJSONRequestBody defines body for CreateToilet for application/json ContentType.
type CreateToiletJSONRequestBody = CreateToiletRequest

// CreateReportJSONRequestBody defines body for CreateReport for application/json ContentType.
type CreateReportJSONRequestBody = CreateReportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// メール確認コード検証
	// (POST /auth/confirm)
	ConfirmSignUp(w http.ResponseWriter, r *http.Request)
	// ログイン
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// ログアウト
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// トークンリフレッシュ
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// ユーザー新規登録
	// (POST /auth/signup)
	SignUp(w http.ResponseWriter, r *http.Request)
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(w http.ResponseWriter, r *http.Request)
	// 現在位置から最適なトイレルートをAIが提案
	// (POST /navigation/route)
	GetRoute(w http.ResponseWriter, r *http.Request)
	// デバイストークン削除（通知停止）
	// (DELETE /notifications/device)
	UnregisterDevice(w http.ResponseWriter, r *http.Request)
	// デバイストークン登録・更新
	// (PUT /notifications/device)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// 現在位置を送信してトイレ不在エリア判定
	// (POST /notifications/location)
	CheckLocationAlert(w http.ResponseWriter, r *http.Request)
	// 指定範囲内のコンビニ店舗一覧を取得
	// (GET /stores)
	ListStores(w http.ResponseWriter, r *http.Request, params ListStoresParams)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams)
	// トイレ情報を投稿（画像はS3アップロード済みのキーを指定）
	// (POST /toilets)
	CreateToilet(w http.ResponseWriter, r *http.Request)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
	// 特定トイレへの報告一覧を取得
	// (GET /toilets/{toiletId}/reports)
	ListReports(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
	// トイレなし報告を送信（画像付き）
	// (POST /toilets/{toiletId}/reports)
	CreateReport(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// メール確認コード検証
// (POST /auth/confirm)
func (_ Unimplemented) ConfirmSignUp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ログイン
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ログアウト
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トークンリフレッシュ
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ユーザー新規登録
// (POST /auth/signup)
func (_ Unimplemented) SignUp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// S3 presigned URL を発行
// (POST /images/presigned-url)
func (_ Unimplemented) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 現在位置から最適なトイレルートをAIが提案
// (POST /navigation/route)
func (_ Unimplemented) GetRoute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// デバイストークン削除（通知停止）
// (DELETE /notifications/device)
func (_ Unimplemented) UnregisterDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// デバイストークン登録・更新
// (PUT /notifications/device)
func (_ Unimplemented) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 現在位置を送信してトイレ不在エリア判定
// (POST /notifications/location)
func (_ Unimplemented) CheckLocationAlert(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 指定範囲内のコンビニ店舗一覧を取得
// (GET /stores)
func (_ Unimplemented) ListStores(w http.ResponseWriter, r *http.Request, params ListStoresParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 指定範囲内のトイレ一覧を取得（マップ表示用）
// (GET /toilets)
func (_ Unimplemented) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ情報を投稿（画像はS3アップロード済みのキーを指定）
// (POST /toilets)
func (_ Unimplemented) CreateToilet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ詳細を取得
// (GET /toilets/{toiletId})
func (_ Unimplemented) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 特定トイレへの報告一覧を取得
// (GET /toilets/{toiletId}/reports)
func (_ Unimplemented) ListReports(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレなし報告を送信（画像付き）
// (POST /toilets/{toiletId}/reports)
func (_ Unimplemented) CreateReport(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ConfirmSignUp operation middleware
func (siw *ServerInterfaceWrapper) ConfirmSignUp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmSignUp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignUp operation middleware
func (siw *ServerInterfaceWrapper) SignUp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignUp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePresignedUrl operation middleware
func (siw *ServerInterfaceWrapper) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePresignedUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoute operation middleware
func (siw *ServerInterfaceWrapper) GetRoute(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterDevice operation middleware
func (siw *ServerInterfaceWrapper) UnregisterDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckLocationAlert operation middleware
func (siw *ServerInterfaceWrapper) CheckLocationAlert(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckLocationAlert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStores operation middleware
func (siw *ServerInterfaceWrapper) ListStores(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStoresParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := r.URL.Query().Get("lat"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		return
	}

	// ------------- Required query parameter "lng" -------------

	if paramValue := r.URL.Query().Get("lng"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStores(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListToilets operation middleware
func (siw *ServerInterfaceWrapper) ListToilets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToiletsParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := r.URL.Query().Get("lat"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		return
	}

	// ------------- Required query parameter "lng" -------------

	if paramValue := r.URL.Query().Get("lng"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListToilets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToilet operation middleware
func (siw *ServerInterfaceWrapper) CreateToilet(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToilet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToilet operation middleware
func (siw *ServerInterfaceWrapper) GetToilet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToilet(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReports operation middleware
func (siw *ServerInterfaceWrapper) ListReports(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReports(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReport operation middleware
func (siw *ServerInterfaceWrapper) CreateReport(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReport(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/confirm", wrapper.ConfirmSignUp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/signup", wrapper.SignUp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/images/presigned-url", wrapper.CreatePresignedUrl)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/navigation/route", wrapper.GetRoute)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notifications/device", wrapper.UnregisterDevice)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/notifications/device", wrapper.RegisterDevice)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notifications/location", wrapper.CheckLocationAlert)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stores", wrapper.ListStores)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets", wrapper.ListToilets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/toilets", wrapper.CreateToilet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets/{toiletId}", wrapper.GetToilet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets/{toiletId}/reports", wrapper.ListReports)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/toilets/{toiletId}/reports", wrapper.CreateReport)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ConfirmSignUpRequestObject struct {
	Body *ConfirmSignUpJSONRequestBody
}

type ConfirmSignUpResponseObject interface {
	VisitConfirmSignUpResponse(w http.ResponseWriter) error
}

type ConfirmSignUp200JSONResponse MessageResponse

func (response ConfirmSignUp200JSONResponse) VisitConfirmSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmSignUp400JSONResponse struct{ BadRequestJSONResponse }

func (response ConfirmSignUp400JSONResponse) VisitConfirmSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthTokens

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse AuthTokens

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201JSONResponse MessageResponse

func (response SignUp201JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SignUp400JSONResponse struct{ BadRequestJSONResponse }

func (response SignUp400JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SignUp409JSONResponse Error

func (response SignUp409JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrlRequestObject struct {
	Body *CreatePresignedUrlJSONRequestBody
}

type CreatePresignedUrlResponseObject interface {
	VisitCreatePresignedUrlResponse(w http.ResponseWriter) error
}

type CreatePresignedUrl200JSONResponse PresignedUrlResponse

func (response CreatePresignedUrl200JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrl401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePresignedUrl401JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRouteRequestObject struct {
	Body *GetRouteJSONRequestBody
}

type GetRouteResponseObject interface {
	VisitGetRouteResponse(w http.ResponseWriter) error
}

type GetRoute200JSONResponse RouteResponse

func (response GetRoute200JSONResponse) VisitGetRouteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRoute401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRoute401JSONResponse) VisitGetRouteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRoute404JSONResponse Error

func (response GetRoute404JSONResponse) VisitGetRouteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UnregisterDeviceRequestObject struct {
}

type UnregisterDeviceResponseObject interface {
	VisitUnregisterDeviceResponse(w http.ResponseWriter) error
}

type UnregisterDevice204Response struct {
}

func (response UnregisterDevice204Response) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnregisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnregisterDevice401JSONResponse) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice200JSONResponse MessageResponse

func (response RegisterDevice200JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RegisterDevice401JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CheckLocationAlertRequestObject struct {
	Body *CheckLocationAlertJSONRequestBody
}

type CheckLocationAlertResponseObject interface {
	VisitCheckLocationAlertResponse(w http.ResponseWriter) error
}

type CheckLocationAlert200JSONResponse LocationCheckResponse

func (response CheckLocationAlert200JSONResponse) VisitCheckLocationAlertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckLocationAlert401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CheckLocationAlert401JSONResponse) VisitCheckLocationAlertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListStoresRequestObject struct {
	Params ListStoresParams
}

type ListStoresResponseObject interface {
	VisitListStoresResponse(w http.ResponseWriter) error
}

type ListStores200JSONResponse struct {
	Stores []Store `json:"stores"`
}

func (response ListStores200JSONResponse) VisitListStoresResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListStores401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListStores401JSONResponse) VisitListStoresResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListToiletsRequestObject struct {
	Params ListToiletsParams
}

type ListToiletsResponseObject interface {
	VisitListToiletsResponse(w http.ResponseWriter) error
}

type ListToilets200JSONResponse struct {
	Toilets []Toilet `json:"toilets"`
}

func (response ListToilets200JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListToilets401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListToilets401JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateToiletRequestObject struct {
	Body *CreateToiletJSONRequestBody
}

type CreateToiletResponseObject interface {
	VisitCreateToiletResponse(w http.ResponseWriter) error
}

type CreateToilet201JSONResponse Toilet

func (response CreateToilet201JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateToilet400JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateToilet401JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet422JSONResponse Error

func (response CreateToilet422JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetToiletRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
}

type GetToiletResponseObject interface {
	VisitGetToiletResponse(w http.ResponseWriter) error
}

type GetToilet200JSONResponse Toilet

func (response GetToilet200JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetToilet401JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet404JSONResponse struct{ NotFoundJSONResponse }

func (response GetToilet404JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListReportsRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
}

type ListReportsResponseObject interface {
	VisitListReportsResponse(w http.ResponseWriter) error
}

type ListReports200JSONResponse struct {
	Reports []Report `json:"reports"`
}

func (response ListReports200JSONResponse) VisitListReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListReports401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListReports401JSONResponse) VisitListReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListReports404JSONResponse struct{ NotFoundJSONResponse }

func (response ListReports404JSONResponse) VisitListReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateReportRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
	Body     *CreateReportJSONRequestBody
}

type CreateReportResponseObject interface {
	VisitCreateReportResponse(w http.ResponseWriter) error
}

type CreateReport201JSONResponse Report

func (response CreateReport201JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateReport400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateReport400JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateReport401JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateReport404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateReport404JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateReport422JSONResponse Error

func (response CreateReport422JSONResponse) VisitCreateReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// メール確認コード検証
	// (POST /auth/confirm)
	ConfirmSignUp(ctx context.Context, request ConfirmSignUpRequestObject) (ConfirmSignUpResponseObject, error)
	// ログイン
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウト
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// トークンリフレッシュ
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// ユーザー新規登録
	// (POST /auth/signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(ctx context.Context, request CreatePresignedUrlRequestObject) (CreatePresignedUrlResponseObject, error)
	// 現在位置から最適なトイレルートをAIが提案
	// (POST /navigation/route)
	GetRoute(ctx context.Context, request GetRouteRequestObject) (GetRouteResponseObject, error)
	// デバイストークン削除（通知停止）
	// (DELETE /notifications/device)
	UnregisterDevice(ctx context.Context, request UnregisterDeviceRequestObject) (UnregisterDeviceResponseObject, error)
	// デバイストークン登録・更新
	// (PUT /notifications/device)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// 現在位置を送信してトイレ不在エリア判定
	// (POST /notifications/location)
	CheckLocationAlert(ctx context.Context, request CheckLocationAlertRequestObject) (CheckLocationAlertResponseObject, error)
	// 指定範囲内のコンビニ店舗一覧を取得
	// (GET /stores)
	ListStores(ctx context.Context, request ListStoresRequestObject) (ListStoresResponseObject, error)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(ctx context.Context, request ListToiletsRequestObject) (ListToiletsResponseObject, error)
	// トイレ情報を投稿（画像はS3アップロード済みのキーを指定）
	// (POST /toilets)
	CreateToilet(ctx context.Context, request CreateToiletRequestObject) (CreateToiletResponseObject, error)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(ctx context.Context, request GetToiletRequestObject) (GetToiletResponseObject, error)
	// 特定トイレへの報告一覧を取得
	// (GET /toilets/{toiletId}/reports)
	ListReports(ctx context.Context, request ListReportsRequestObject) (ListReportsResponseObject, error)
	// トイレなし報告を送信（画像付き）
	// (POST /toilets/{toiletId}/reports)
	CreateReport(ctx context.Context, request CreateReportRequestObject) (CreateReportResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ConfirmSignUp operation middleware
func (sh *strictHandler) ConfirmSignUp(w http.ResponseWriter, r *http.Request) {
	var request ConfirmSignUpRequestObject

	var body ConfirmSignUpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmSignUp(ctx, request.(ConfirmSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmSignUp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConfirmSignUpResponseObject); ok {
		if err := validResponse.VisitConfirmSignUpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(w http.ResponseWriter, r *http.Request) {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx, request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		if err := validResponse.VisitSignUpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePresignedUrl operation middleware
func (sh *strictHandler) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	var request CreatePresignedUrlRequestObject

	var body CreatePresignedUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresignedUrl(ctx, request.(CreatePresignedUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresignedUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePresignedUrlResponseObject); ok {
		if err := validResponse.VisitCreatePresignedUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRoute operation middleware
func (sh *strictHandler) GetRoute(w http.ResponseWriter, r *http.Request) {
	var request GetRouteRequestObject

	var body GetRouteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoute(ctx, request.(GetRouteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRouteResponseObject); ok {
		if err := validResponse.VisitGetRouteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterDevice operation middleware
func (sh *strictHandler) UnregisterDevice(w http.ResponseWriter, r *http.Request) {
	var request UnregisterDeviceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterDevice(ctx, request.(UnregisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterDeviceResponseObject); ok {
		if err := validResponse.VisitUnregisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckLocationAlert operation middleware
func (sh *strictHandler) CheckLocationAlert(w http.ResponseWriter, r *http.Request) {
	var request CheckLocationAlertRequestObject

	var body CheckLocationAlertJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckLocationAlert(ctx, request.(CheckLocationAlertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckLocationAlert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckLocationAlertResponseObject); ok {
		if err := validResponse.VisitCheckLocationAlertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStores operation middleware
func (sh *strictHandler) ListStores(w http.ResponseWriter, r *http.Request, params ListStoresParams) {
	var request ListStoresRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStores(ctx, request.(ListStoresRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStores")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStoresResponseObject); ok {
		if err := validResponse.VisitListStoresResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListToilets operation middleware
func (sh *strictHandler) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	var request ListToiletsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListToilets(ctx, request.(ListToiletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListToilets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListToiletsResponseObject); ok {
		if err := validResponse.VisitListToiletsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToilet operation middleware
func (sh *strictHandler) CreateToilet(w http.ResponseWriter, r *http.Request) {
	var request CreateToiletRequestObject

	var body CreateToiletJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToilet(ctx, request.(CreateToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateToiletResponseObject); ok {
		if err := validResponse.VisitCreateToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetToilet operation middleware
func (sh *strictHandler) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request GetToiletRequestObject

	request.ToiletId = toiletId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetToilet(ctx, request.(GetToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToiletResponseObject); ok {
		if err := validResponse.VisitGetToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReports operation middleware
func (sh *strictHandler) ListReports(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request ListReportsRequestObject

	request.ToiletId = toiletId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListReports(ctx, request.(ListReportsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReports")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReportsResponseObject); ok {
		if err := validResponse.VisitListReportsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateReport operation middleware
func (sh *strictHandler) CreateReport(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request CreateReportRequestObject

	request.ToiletId = toiletId

	var body CreateReportJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateReport(ctx, request.(CreateReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateReportResponseObject); ok {
		if err := validResponse.VisitCreateReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RcW1Mbx57/KqrZfdito1jY5FTtUpUHbCcpztoJxWXz4Lhcg9SIiaUZZWaETVxUaWbA",
	"CBAHQrAxmBxsHwwyBAEhiTHC5sO0ZkY88RW2unvu6pEEGOXsk5E03f3v//X3v4wfMXEhnRF4wMsS0/GI",
	"ybAimwYyEPEnWeBSQO5KoL8TQIqLXEbmBJ7pYKCWh+oa1H7puslEGQ59lWHlISbK8GwaMB3u0igjgu+z",
	"nAgSTIcsZkGUkeJDIM2iPQcFMc3KTAeTzXLoSXkkg9ZKssjxSWZ0dBQtljICLwFMz3U20QO+zwJJRp/i",
	"Ai8DHv/JZjIpLs4i4mLfSYjCR55j/l0Eg0wH828x964x8qsU+1wUBZEcFbzhJlR3oFqE6juo5SsHM8b2",
	"P5nRKPOVIH8hZPlEi0h4D7UjRIJSqK5PQ2UNKtNQnYTKJlTGEDn9PJuVhwSR+wG0gKTq5ky1eIS4or2B",
	"2hGDnrAWoT07s/JQn3Af8ESZRCEDRJkjwmPjcSBJ+FesW35ZRxnwMMOJQOriKdqmvsKyKBNZYI7sQG3f",
	"WJnUp94ZK6snS3OnR3lzY/70aNLVI46XQRKIaHMuEX6wCAZFIA2FPTDq1eA7vmu4+wZ28d7mrkOPMPAd",
	"iMvoyBsCP8iJ6V4uyfdnPCrt51icPIUFeENIADrb0iyX8hkT+Sba4B72UzWHUOkVASuDHpARRDmUXC7N",
	"JsH/gBGK/HIFx2FgzV2EOaRHxvQLc6Gsa7NQKfW2Q3UbqVSUJiHWUl//vvqLPf3HKXPusbmwx0SZNPvw",
	"FuCT8hDT8de2tkYMcMh19g+/eR/2ZqE3HwRpNgVuCFlidwEiX+8buQ1zoeiwQM9NG092EcEcz6Wzaaaj",
	"jaqzofzsbYfKFjIKTYPaItQQ36A2aRzkoXIMlZLF1FB+1qHWXHh7PmrT2ZTMZbJiRpBCObG2bD4vmctj",
	"Z92bF2RA0SrlZ6iUKuWn1YlNc2GvWnymj782fhlrrAmOIkjdQExzksRRtetwUf/pJVQO0Cnvj82FYrW4",
	"p8/uQKWgH49X1xWoTLvcHRCEFGB5tLkkCyKgRk11H2r7UPsJatP64WI1v4jDZ6Mw6Ndbe/eoV4NdiUZ9",
	"2kiTC/X2NN2/CYa5OOgBSU6SRewgQi0ggR91XKj/2l/cuB2JRTq7v5IiUJuA2hwSvt+T07Q0k2JlxBq0",
	"IeCRctxhOEFiogzLJ0QBs+oBGPCQHsIxL3GebWlXJoGP4omJ9wUP2XQmhZb8b+etrpudfV1ff3Xv856e",
	"r3uoZgYkiU0GFgZwBVQKBFpAZQMqSw2ljylxt6bd4ZZAYv6NIRC/HyqxFCv7okZCyA6kgHs+n00PEOtL",
	"8cmmngxQig4gi5sgkoC8WiqHWOkrwIoDI8QD1+rW1fvpSvm1/ngceUQ3xhSgokJ1OsxCecCKQJLdTdlU",
	"6utBpuNOfVhkPT96NwiLjJWcvjMG1SmolBwqTo/yONj9CNUCVHb5bCpF4An6i0UsxICY+Ddu0EJqvYDm",
	"Op1NKwcz+krxJLdsrr6G6vxJTqkcv0QBVVmlXzYglSBDg7ygyyrJhZt+0wAkymRYSXogiAnf086XzSIW",
	"ZwGN1tvEMMI1imqU+sS6OfcYOfZSoXL4GPPzA+FqQ7LqmWK3CCQuyYNEv5iqB/MQYu/Di2nQ1x/lobIE",
	"1WkHN93uuv05VI+xdiwi4Gl7ShQcYt9lQNKOFLEM7/79AAxkKJ4zylihgoYMrBPNheJJbsFzFMn17ome",
	"QIG4Zn+LQGNjJ+3lgktFY6aGyblOOtHfcyssc3BUor3t7JhM3YTaU6geQHUDR7U8QWCnR3lj6olZPDaW",
	"VKhsGYUJvbTsS1Rc7mczKYFFF6MdEMnYN4909/dF+ntu+cCDyDXUVXd7H3qon6z0eDKbUCU+WxLle5p+",
	"JtaaWlvBcDzRGYhdrAw+kbk0oLHUWnJ9hJo+YS5Y/K7PSm8aQvkJ0duVaKKqgfAhK2elWgmj1DIjg8Rn",
	"PeC+kOQ59LW+88ZYLZ/klk+Uv0cjIkAMAonPKgcz5DuPGdrLMcAjz1Et3FvVORv0dG4Z9dZ3HBY6HHKu",
	"GPUIjCpmISuDm0C2IkgAU3KSzPJxcNupRwVqEW9/Pnn+CkVZ7SV2jXmobRG7agLVJLKiFW/jAp+gbG9M",
	"5qrrirGknjz9qX5xISOkRlIcT/XeRQT4Eez3JGjazwgEam+wz94/PcrrK7v6831jdtZcKJsLxRDfIDto",
	"pRmMEhCdbIf7AFdrGeG5T6jIGqHKQOSY/aCvFCvvZ8z3JRQ/3u7oh+vNScnCnvX3+73Q9H5p9mEPkLIp",
	"2RL4IJtNyUxHew2gm50zXuZJqPXAyhICemsbVs7KPiQ56189+evVWgU5Ey622BsW1UT0M6m2yCAtNVIG",
	"r32NOqexosiOYEeUTSaBJFOz3+sgIQrx+xGoFMyFVSM/R+AQYYzxdKJxnupuHrXppt24QRHsDPCS5+L3",
	"Sfn5kb8CgOVjf7x6DmDqWf5fZ4apHsKo90f5PKVcmkiIQJKo0WZAZEn92Xb9EhgG/D2QQv8gQ2DTXGrk",
	"XpoVsaqxD4hTRkp6T5KFDLJ6Fj0xwqbZH9j7KNoJ8hAQqfFiiJXCsi/HNAxtXH+xh3RlqXxS+NWuRE1D",
	"5Q1UHoelYR8/B7X7D76MWy0jXKbtf2KZMf4QMQ6mq7tvTzbG9ckZ/XCRHqidQs55azSYnKjH6G3p0VTB",
	"ZfPHRT0B34bBaDU3DrV1XID5A2pHuBBVs0ugsNlEvZIKXR01ITlEM8A1UKQ8R+2xuZJiCJILqWBWl5Z1",
	"5T0pO+Pa4x/NlC/pxUZa3TAMF8rcMPgMav8gqWD1ZdFcO6wcbCNAmBaGQeIzP2FbUM1DdUqfnDpZWvMh",
	"RLQRxml4GdXcm1f6M0FJlNskzqbFVAiDrSpQAyXg88I1UA9s9WpBfRCLOAbiWZGTR3pR1LVzeoTfhc4s",
	"ChmPmAHAikD8wr7z377pY4KIozPN/iDwkRtkIQ67S4fVlwWCQSJdNyM4W4rEIp24AxWx65k41mNNwoe4",
	"bByS5Qzp4XH8oFC/Gu2tWxFgZXl0dV4f3zNWJqFWNtZWzN9eEXq+AQO4MrGIy5l72I28hdoG2lApdXZ3",
	"wZz6LU+6hfrqofl8DSo7Ef8dYU792zd9EajORzqtFiYGohGoPcOKnkPbKluV8rPKwd/xhsR/VI5/1ref",
	"oQ1722FOIV+SRMlziieJgjnlWx5qWyRLsLGd86Rdi4z0AnGYi4PIX+xfLBCEz0aM5WQrong456BD2zwj",
	"nd1dTJQZBqJk1SivtF1pQxYgZADPZjimg2m/0nalHYMEeQgrTIzNykMxqxmHI4BA0BCKA5g6ZGX+xqGl",
	"xUCSrwuJkY/W/KU2J0f91mgVLn3d+WttbR+NhmAZj9KKNl8dVjdnjPycPrWKmPspOZ62q0NmzDNBgC03",
	"m06z4ggOUSSH3CLbuinb2kq1iJtobFLCPhSZ9F20mIgsJSQ5PlxguHZ6SYLy1WVbLCBPp586ubAN1V2S",
	"33oldLVVEwr62p7xZLFGxi5V9SUqZOW6IkW/1zD3UxrwISe+guo68jxBVtRXVt9ohzfQ4EaFL8TcuTt6",
	"l3ZV6+A6t7VKceHX7fEPNlyGItMqjP9i+rwJtSfYyWs40L2+sCg9onLboLXn1JGcxCX5bCZccJcaJM4R",
	"Ha62NDqQPBRL6fQoH/DqpG1GstTTo8lzhQ+05L9bMQRmBSaMtyaRbqjvTiZmqmsTNYrkpnPG093q+ixh",
	"Al2FMHCWYk5L4ZMsydxCcAdGwN7OyyXpFa1j1mJXQO0vUSTjdmP6e25FCFpvnYf3tYMQAVCdJzR45E2E",
	"bEmcZ4e5JGEILsd5pV0zr1UpTyGkr8x5qp9bOB2Zwa3msdMjBeZmoLYC1WOo7ZsLRYySwyA1VDbM3wvV",
	"tzvVYt4sLWJE7gfZ6BGnuogu41Yd16vHC4gaC4b7VfNLIOMy52XFJm+9u8Wa6C8GU52DL6c5p96hRZ9e",
	"vifTfyxWPxwG5jRoQ61nsgN/MwBtY6zkTpQ3aDM3NbPYBNX5zi6oFCx2uYbi2oZtLJ6RDClGJoiIoaQA",
	"MR2/FvbzpP0NRDI11RQ8JAWaVqJC+vQVoeP0KE/mSnRlxdh+ZXWhbAZ5+cHcxYMC1ILwogNdyGbIMSil",
	"sJOx00JBCts20ZDwkR6kHriltgnVVye5X/Xx17inXrLmYZQtMqdHdxQ9tQL6+O4ifGbuXzCD9mCkP1P9",
	"LA3Qysbz34ynu3W0rtYyU1agqRPM0Bm414oA1D6ZudNLy8bKqrk8BpUtnwdxRqoa62NbpfwHVEr6i9/0",
	"uTzMKZ8PA16+LnKJJDB/L5gLe1DZ+JavtQiozuPbb0L1F1zhwk1Gqsri6Tg7lnamgChfWimBMjPYYo2l",
	"jwTSAkl+TS8tm7/PGf9YaYXe0hUEA5PAXJ7jnAiJDTQZV7ExG5OAVmfgJLmXPBL1vZhzJ6jilYNt/Vhz",
	"+ur4dZzvs0Accd/HIQ2oJl7FCZ/uDDnV7r5TT8UNr496KqlC6zNT+ocx6uwHjQ6RTXC4ru8e7fT+r7a1",
	"tXmb+eSj08+nzYEh9biQGfjbe64eNNXUJw3jmnY+rQVJ67hT7AmPolcOctX1jVbYE5mAM3fG9Oe/Yrda",
	"qh2MJ9RAdV6ffap/WPRYkn0xbEKkJ1TfhvqsZ2qM6NLs5NJM4f+fbnsE1JRy2+NLDbTb3rYZ9fb46D9R",
	"w/1EOIqNXZivr+sOgFkK79wVj5rRIA7p6OsfCjCneNpeKKMOtN69IxmIBtI0w1jHM2iI11lEQWVLn50x",
	"nr2AOdWZOoTKTuTTa9ciUJ2vl5p7X566rGYV5f2sFlcjnYm7Gs2zxn7tIqSPxVrZYTHh78WrkedJ/K9d",
	"u/zE31Y970uARYKQoPIEvx2xiRXzn1BZPXNO4Z9AUucJ00+P8vaxO73tdd6VIzPaaJ13LrvG9DzBJvbI",
	"nkQYDY07XwLZUftA1KGx0H0k5kw5XNgRn09nHYZW3+ybv+1etKRUf5HzLvU5hU5opKGERpKLkQmP+sih",
	"x3rmz5NhcMjeobm58U8yRd8omNrbNoUV8YjRhSLp5eqGOfkO+RXX0xzgHN2lmqYtDgdCQ6z/FWa7FhV4",
	"i1mdb/RmbsDb4LAZiNj2IMsizCnkNRWobNqTXUWSduqzi+bcYxK35wqVg5y3Sq/vkFeX1tsr5T8q5deV",
	"gyk8uYy2svfxxvdpqE5WJzb16SekDlgvllsadUGDuCwY4H9BvcUwwDa2MJshMmtpcD+bmbUcDdD+VwCo",
	"lIhJXQJEIIdYJmDXcRygUCk/g8qMP/67foEcKQ7TCzDdopDIxrEF/0dnd1fkS1YGD9iRyF8it9j0QIL9",
	"TybK4P4qHsqTOmIxNsNdsUaUr8SFdGz4KrYN6+BH1KGW06O8NTpnvUdKEkDc1K0tlNTm1KR04i60MmnK",
	"0uBYd8kp0Tqu0/f/vNA28Y6k4iyHIgXfPWxm0+jxj+4h7DyFbqb+6p08dLfytHNouwUrstXiNqnW2ct9",
	"xbraHWx3H3Tz7g5W43X07uj/BQAA//9mVsEJYkcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
