// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CognitoAuthScopes = "cognitoAuth.Scopes"
)

// Defines values for CreateToiletRequestBrand.
const (
	CreateToiletRequestBrandDailyYamazaki CreateToiletRequestBrand = "daily_yamazaki"
	CreateToiletRequestBrandFamilyMart    CreateToiletRequestBrand = "family_mart"
	CreateToiletRequestBrandLawson        CreateToiletRequestBrand = "lawson"
	CreateToiletRequestBrandMiniStop      CreateToiletRequestBrand = "mini_stop"
	CreateToiletRequestBrandOther         CreateToiletRequestBrand = "other"
	CreateToiletRequestBrandSevenEleven   CreateToiletRequestBrand = "seven_eleven"
)

// Valid indicates whether the value is a known member of the CreateToiletRequestBrand enum.
func (e CreateToiletRequestBrand) Valid() bool {
	switch e {
	case CreateToiletRequestBrandDailyYamazaki:
		return true
	case CreateToiletRequestBrandFamilyMart:
		return true
	case CreateToiletRequestBrandLawson:
		return true
	case CreateToiletRequestBrandMiniStop:
		return true
	case CreateToiletRequestBrandOther:
		return true
	case CreateToiletRequestBrandSevenEleven:
		return true
	default:
		return false
	}
}

// Defines values for CreateToiletRequestToiletType.
const (
	CreateToiletRequestToiletTypeSeparated CreateToiletRequestToiletType = "separated"
	CreateToiletRequestToiletTypeShared    CreateToiletRequestToiletType = "shared"
)

// Valid indicates whether the value is a known member of the CreateToiletRequestToiletType enum.
func (e CreateToiletRequestToiletType) Valid() bool {
	switch e {
	case CreateToiletRequestToiletTypeSeparated:
		return true
	case CreateToiletRequestToiletTypeShared:
		return true
	default:
		return false
	}
}

// Defines values for PresignedUrlRequestContentType.
const (
	Imagejpeg PresignedUrlRequestContentType = "image/jpeg"
	Imagepng  PresignedUrlRequestContentType = "image/png"
	Imagewebp PresignedUrlRequestContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the PresignedUrlRequestContentType enum.
func (e PresignedUrlRequestContentType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for ToiletBrand.
const (
	ToiletBrandDailyYamazaki ToiletBrand = "daily_yamazaki"
	ToiletBrandFamilyMart    ToiletBrand = "family_mart"
	ToiletBrandLawson        ToiletBrand = "lawson"
	ToiletBrandMiniStop      ToiletBrand = "mini_stop"
	ToiletBrandOther         ToiletBrand = "other"
	ToiletBrandSevenEleven   ToiletBrand = "seven_eleven"
)

// Valid indicates whether the value is a known member of the ToiletBrand enum.
func (e ToiletBrand) Valid() bool {
	switch e {
	case ToiletBrandDailyYamazaki:
		return true
	case ToiletBrandFamilyMart:
		return true
	case ToiletBrandLawson:
		return true
	case ToiletBrandMiniStop:
		return true
	case ToiletBrandOther:
		return true
	case ToiletBrandSevenEleven:
		return true
	default:
		return false
	}
}

// Defines values for ToiletToiletType.
const (
	ToiletToiletTypeSeparated ToiletToiletType = "separated"
	ToiletToiletTypeShared    ToiletToiletType = "shared"
)

// Valid indicates whether the value is a known member of the ToiletToiletType enum.
func (e ToiletToiletType) Valid() bool {
	switch e {
	case ToiletToiletTypeSeparated:
		return true
	case ToiletToiletTypeShared:
		return true
	default:
		return false
	}
}

// CreateToiletRequest defines model for CreateToiletRequest.
type CreateToiletRequest struct {
	// Address 住所
	Address *string `json:"address,omitempty"`

	// Brand コンビニブランド
	Brand CreateToiletRequestBrand `json:"brand"`

	// ImageKey S3にアップロード済みの画像キー
	ImageKey *string `json:"imageKey,omitempty"`

	// Lat 緯度
	Lat float64 `json:"lat"`

	// Lng 経度
	Lng float64 `json:"lng"`

	// Name コンビニ店舗名
	Name string `json:"name"`

	// Note その他自由記入欄
	Note *string `json:"note,omitempty"`

	// RequiresPermission 店員への使用許可が必要か
	RequiresPermission bool `json:"requiresPermission"`

	// ToiletType shared: 男女共用, separated: 男女別
	ToiletType CreateToiletRequestToiletType `json:"toiletType"`
}

// CreateToiletRequestBrand コンビニブランド
type CreateToiletRequestBrand string

// CreateToiletRequestToiletType shared: 男女共用, separated: 男女別
type CreateToiletRequestToiletType string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PresignedUrlRequest defines model for PresignedUrlRequest.
type PresignedUrlRequest struct {
	// ContentType アップロードする画像のMIMEタイプ
	ContentType PresignedUrlRequestContentType `json:"contentType"`
}

// PresignedUrlRequestContentType アップロードする画像のMIMEタイプ
type PresignedUrlRequestContentType string

// PresignedUrlResponse defines model for PresignedUrlResponse.
type PresignedUrlResponse struct {
	// ExpiresIn URL有効期限（秒）
	ExpiresIn int `json:"expiresIn"`

	// ImageKey S3オブジェクトキー（投稿時に指定）
	ImageKey string `json:"imageKey"`

	// UploadUrl S3 presigned PUT URL
	UploadUrl string `json:"uploadUrl"`
}

// Toilet defines model for Toilet.
type Toilet struct {
	Address   *string     `json:"address,omitempty"`
	Brand     ToiletBrand `json:"brand"`
	CreatedAt time.Time   `json:"createdAt"`

	// CreatedBy 投稿者ユーザーID
	CreatedBy *string `json:"createdBy,omitempty"`

	// ImageUrl トイレ画像URL
	ImageUrl string  `json:"imageUrl"`
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`

	// Name コンビニ店舗名
	Name               string             `json:"name"`
	Note               *string            `json:"note,omitempty"`
	RequiresPermission bool               `json:"requiresPermission"`
	ToiletId           openapi_types.UUID `json:"toiletId"`

	// ToiletType shared: 男女共用, separated: 男女別
	ToiletType ToiletToiletType `json:"toiletType"`
	UpdatedAt  *time.Time       `json:"updatedAt,omitempty"`
}

// ToiletBrand defines model for Toilet.Brand.
type ToiletBrand string

// ToiletToiletType shared: 男女共用, separated: 男女別
type ToiletToiletType string

// ToiletId defines model for toiletId.
type ToiletId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListToiletsParams defines parameters for ListToilets.
type ListToiletsParams struct {
	// Lat 中心緯度
	Lat float64 `form:"lat" json:"lat"`

	// Lng 中心経度
	Lng float64 `form:"lng" json:"lng"`

	// Radius 検索半径（メートル）
	Radius *int `form:"radius,omitempty" json:"radius,omitempty"`
}

// CreatePresignedUrlJSONRequestBody defines body for CreatePresignedUrl for application/json ContentType.
type CreatePresignedUrlJSONRequestBody = PresignedUrlRequest

// CreateToiletJSONRequestBody defines body for CreateToilet for application/json ContentType.
type CreateToiletJSONRequestBody = CreateToiletRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(w http.ResponseWriter, r *http.Request)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams)
	// トイレ情報を投稿
	// (POST /toilets)
	CreateToilet(w http.ResponseWriter, r *http.Request)
	// トイレ情報を削除
	// (DELETE /toilets/{toiletId})
	DeleteToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// S3 presigned URL を発行
// (POST /images/presigned-url)
func (_ Unimplemented) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 指定範囲内のトイレ一覧を取得（マップ表示用）
// (GET /toilets)
func (_ Unimplemented) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ情報を投稿
// (POST /toilets)
func (_ Unimplemented) CreateToilet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ情報を削除
// (DELETE /toilets/{toiletId})
func (_ Unimplemented) DeleteToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トイレ詳細を取得
// (GET /toilets/{toiletId})
func (_ Unimplemented) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreatePresignedUrl operation middleware
func (siw *ServerInterfaceWrapper) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePresignedUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListToilets operation middleware
func (siw *ServerInterfaceWrapper) ListToilets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToiletsParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := r.URL.Query().Get("lat"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		return
	}

	// ------------- Required query parameter "lng" -------------

	if paramValue := r.URL.Query().Get("lng"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListToilets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToilet operation middleware
func (siw *ServerInterfaceWrapper) CreateToilet(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToilet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteToilet operation middleware
func (siw *ServerInterfaceWrapper) DeleteToilet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteToilet(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToilet operation middleware
func (siw *ServerInterfaceWrapper) GetToilet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toiletId" -------------
	var toiletId ToiletId

	err = runtime.BindStyledParameterWithOptions("simple", "toiletId", chi.URLParam(r, "toiletId"), &toiletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toiletId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CognitoAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToilet(w, r, toiletId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/images/presigned-url", wrapper.CreatePresignedUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets", wrapper.ListToilets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/toilets", wrapper.CreateToilet)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/toilets/{toiletId}", wrapper.DeleteToilet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/toilets/{toiletId}", wrapper.GetToilet)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type CreatePresignedUrlRequestObject struct {
	Body *CreatePresignedUrlJSONRequestBody
}

type CreatePresignedUrlResponseObject interface {
	VisitCreatePresignedUrlResponse(w http.ResponseWriter) error
}

type CreatePresignedUrl200JSONResponse PresignedUrlResponse

func (response CreatePresignedUrl200JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrl401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePresignedUrl401JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListToiletsRequestObject struct {
	Params ListToiletsParams
}

type ListToiletsResponseObject interface {
	VisitListToiletsResponse(w http.ResponseWriter) error
}

type ListToilets200JSONResponse struct {
	Toilets []Toilet `json:"toilets"`
}

func (response ListToilets200JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListToilets401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListToilets401JSONResponse) VisitListToiletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateToiletRequestObject struct {
	Body *CreateToiletJSONRequestBody
}

type CreateToiletResponseObject interface {
	VisitCreateToiletResponse(w http.ResponseWriter) error
}

type CreateToilet201JSONResponse Toilet

func (response CreateToilet201JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateToilet400JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateToilet401JSONResponse) VisitCreateToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteToiletRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
}

type DeleteToiletResponseObject interface {
	VisitDeleteToiletResponse(w http.ResponseWriter) error
}

type DeleteToilet204Response struct {
}

func (response DeleteToilet204Response) VisitDeleteToiletResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteToilet401JSONResponse) VisitDeleteToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteToilet404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteToilet404JSONResponse) VisitDeleteToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetToiletRequestObject struct {
	ToiletId ToiletId `json:"toiletId"`
}

type GetToiletResponseObject interface {
	VisitGetToiletResponse(w http.ResponseWriter) error
}

type GetToilet200JSONResponse Toilet

func (response GetToilet200JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetToilet401JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetToilet404JSONResponse struct{ NotFoundJSONResponse }

func (response GetToilet404JSONResponse) VisitGetToiletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// S3 presigned URL を発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(ctx context.Context, request CreatePresignedUrlRequestObject) (CreatePresignedUrlResponseObject, error)
	// 指定範囲内のトイレ一覧を取得（マップ表示用）
	// (GET /toilets)
	ListToilets(ctx context.Context, request ListToiletsRequestObject) (ListToiletsResponseObject, error)
	// トイレ情報を投稿
	// (POST /toilets)
	CreateToilet(ctx context.Context, request CreateToiletRequestObject) (CreateToiletResponseObject, error)
	// トイレ情報を削除
	// (DELETE /toilets/{toiletId})
	DeleteToilet(ctx context.Context, request DeleteToiletRequestObject) (DeleteToiletResponseObject, error)
	// トイレ詳細を取得
	// (GET /toilets/{toiletId})
	GetToilet(ctx context.Context, request GetToiletRequestObject) (GetToiletResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreatePresignedUrl operation middleware
func (sh *strictHandler) CreatePresignedUrl(w http.ResponseWriter, r *http.Request) {
	var request CreatePresignedUrlRequestObject

	var body CreatePresignedUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresignedUrl(ctx, request.(CreatePresignedUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresignedUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePresignedUrlResponseObject); ok {
		if err := validResponse.VisitCreatePresignedUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListToilets operation middleware
func (sh *strictHandler) ListToilets(w http.ResponseWriter, r *http.Request, params ListToiletsParams) {
	var request ListToiletsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListToilets(ctx, request.(ListToiletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListToilets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListToiletsResponseObject); ok {
		if err := validResponse.VisitListToiletsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToilet operation middleware
func (sh *strictHandler) CreateToilet(w http.ResponseWriter, r *http.Request) {
	var request CreateToiletRequestObject

	var body CreateToiletJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToilet(ctx, request.(CreateToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateToiletResponseObject); ok {
		if err := validResponse.VisitCreateToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteToilet operation middleware
func (sh *strictHandler) DeleteToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request DeleteToiletRequestObject

	request.ToiletId = toiletId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteToilet(ctx, request.(DeleteToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteToiletResponseObject); ok {
		if err := validResponse.VisitDeleteToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetToilet operation middleware
func (sh *strictHandler) GetToilet(w http.ResponseWriter, r *http.Request, toiletId ToiletId) {
	var request GetToiletRequestObject

	request.ToiletId = toiletId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetToilet(ctx, request.(GetToiletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetToilet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToiletResponseObject); ok {
		if err := validResponse.VisitGetToiletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ7VMbxxn/V262/dBOz0gU54u+4eBkSEjCYKg/UMaz6BZxju7Fe3u2ZUYznM40Ei+1",
	"xyGmNLSuUwwyjkUIbk14MX/Mcjr5k/+Fzu6eTifphOjYJv5k3XH7vD/P7/esZ0Da0ExDRzqxQGoGmBBD",
	"DRGE+RMx1Cwigwr7rSArjVWTqIYOUoC6RVpYp+6PgwNABip7ZUIyDWSgQw2BVOOoDDC6YasYKSBFsI1k",
	"YKWnkQaZzCkDa5CAFLBtlX1JciY7axGs6hmQz+fZYcs0dAtxey5BZQTdsJFF2FPa0AnS+U9omlk1DZlx",
	"iesWs3Amoua3GE2BFPhNouFrQvzVSlzG2MBCVauHW7SwTQtlWviFusWTvaXq83+DvAy+NMgnhq0r52TC",
	"EXUPmQnOYm1jgTrr1FmghRJ1tqhzl5kzpkObTBtYvYPOwaTa1lKtfMii4j6l7iFgXwSHmMyPMYIEjfLc",
	"RzJlYsNEmKgii1BRMLKs9qI6ObpXLc2214EMJjHU46qwsEvdXep+S90F6j7kNu1StwRkgHRbA6lxYKGb",
	"SL+GsuwfIIMpqKnZ3DUNYgJkkIW3WFhkoKm6es0ihglkoED2RQ5q8A78WgUyMMg0wmAixixVgxn0Ocq1",
	"W3aljzrPaOEH6rrUXaHuc5ZFt1TdK1LnmDoVf/nAc+/RAnsf53AWknah/sttb3+DeVHvG8WwJ7OoIUC3",
	"tUmEuQA9EyPgP4tnFiD6+LSIe/srteKKd3+Jhfs21Mws4l8c8FTsXhADQjxI1b2F2k8vX2/OeaUlb38l",
	"zmfdIHEanX9Qp3Jy8LD2zZa/vFMr/82be1L98S7LGrw9hPQMmQapj5LJGInB5LGGEdZUy1JFCzTL9/ZX",
	"vG8fU2ePaTk69pfLtfKOd2+bOove8Vxtw6HOQsPaScPIIqgz4WLCjfL3rUKtaYiRkpL85Zfek11vbsdf",
	"LsuShdh4JZE/FJ9ES5UfAjIIv4spunx0no6LLNX7Q5SNyH2TfbGRaMg2Jq+jNGE+ib5v69i0oXAnG1n+",
	"U//Q4ED/6OBXX167PDLy1UhcPjVkWTDTcrBlrFJnUUxW6mxSZxV085db0hAd58MwRpaa0ZEyhrMdZ1Aw",
	"JeOz19631FmlhYWgaZ3KF4NfXKaFY17gK5EM8nmQuG4iFn/xYOqN37fQpNk9pVHTuvsn0LHdQXTbZPke",
	"jKn4sZGh6lrJm/+luvbo9er9N4dFf/PBm8NStI37Iv2k6gRlxFA4deAVtlivF/ZoYZOlmDEEFr43h8Xq",
	"/Hd++bi6WqDOs+riN17l70JdW8nYZtaAzLE4BZJZ91waHhuVxkaGopPMxmrX6mmIj7giR2IVF2+BZqfC",
	"WGe8OhcYSnPUVfpJE6dSIEEXiKoh0PnIpZhMimTVZueou8G5x3+pe8hpXjz+xWYr5IeiZ86SqxD0zo5u",
	"HzSMnRGNOgGLYN1dGPKvhUKsU5X/r+ZaWjGyH5yCYWGBdYezaBu0tzGjqShtY5XkrjC6WkeBjK4So99m",
	"FGIGTCKIEf6k7sxnV0dBK//t1+AdQ5c+Fgcl6iz6q/u1x4sCIKTBAWnU+BrpUkLqT6eRZYlHEJBknmiu",
	"pBGfaUJMwbRVfcrownGdSthYJ0dL/lGl6s55/9qhhQfe3E51rUTdg+r6mv/iB2HPVTTJsWyFo+4O7+aX",
	"1N1kAp1K//AgnS38WQ84vbNN3e844u1yYGZrRujolYHPJVp44H//ovrXJ17xqb9c5mepe59BpUB0zr2p",
	"sy31Dw9Kn0KCbsGcRJ1KKKW/vqlgiTqb0mdXR5nQ6voa08/EsbCoJGjAKLcv1rvwnwKZmQogg5sIiz4C",
	"vT3JniQrTMNEOjRVkAJ9PcmePiDzxZSnO8HLyUqEOHLBFrPLNARHYOOdr0us+YJlJgq3QeUhi1wylNw7",
	"27biGEu+uWHY5ty6Df8xmXxPJgSkImb/a0Dw2MiQJGq/WrzvzT9isb+Y7O2kKLQ80bSwRhsTpMZbWnJ8",
	"Ij8hA8vWNIhzrRyAGcBKktvACgdmrJCEWWCCiU6IqcHDlUExOR5SLTIafCM33X6Mt22ne8+9Yzfcwfid",
	"xw0b4Vzj0kOMrjPcd3TCq7zcQWt9cYvVykflO9Uqhoi3NO+9uvvmsEjdx5wHF6n7TDC3ODswVFTbAlHV",
	"CpqCdpaAVG+SEUoN3lY1BjMfiUdVF4+9cWyTpf6t6r2ZrkUqQSVIs7p1RED78qFhEGOY64BjVhzkxNzn",
	"1Gf33mxtY/M8OkawbX/7rvf9z95f5poAhBvBoOPeQ+/VCk9zMF1rj8v++r6/XA5oetBZoa95ORyZp4KV",
	"oFYBRjnlUHWIWtR5xd4XHOpsCN4pgIuDQX3d2j7ZX/BKS9R5Jl3pk9imHrOfrdBZRzjCfjuPpDq/5wjD",
	"oxARDeTYWR/k/P1M+bi7sTNN+d53ZkK9pttLM9jQIpM82b0uI9ex51DK7dUjjI4t0MjsT8zUuWZeFGwW",
	"CYLeXAED/H1YAS1QEOdV45NEyGZjhtbFmDun0vzr1fW3wk126GL3Q+Fl9dvGWpjcYRjEQuuniLyHaCbP",
	"oRlC72tPd/0XP33YGRI2hmM8vhu4aHwzntgMY0Ox0+xB+l2Uuf9BGoLapAJ/D2TAiTLfVaxUIgFNtSdY",
	"lXvShpa42ctTFSjueBdQB4KKv3rwevFn6h6ENjf9r5EF2hlJ/cK8dfI3zga8Lz+R/18AAAD//wt1XmfV",
	"GgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
